version: '3.5'

services:
  namesrv:
    image: apache/rocketmq:4.9.4
    ports:
      - 9876:9876
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/data/rocketmq/namesrv/logs:/home/rocketmq/logs
      - ${LOCAL_WORKSPACE_FOLDER}/data/rocketmq/namesrv/store:/home/rocketmq/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command: [ "sh", "mqnamesrv" ]
    networks:
      - dev-network

  broker:
    image: apache/rocketmq:4.9.4
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER}/data/rocketmq/broker/logs:/home/rocketmq/logs
      - ${LOCAL_WORKSPACE_FOLDER}/data/rocketmq/broker/store:/home/rocketmq/store
      - ${LOCAL_WORKSPACE_FOLDER}/data/rocketmq/broker/brokerconf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128m"
    command:
      [
        "sh",
        "mqbroker",
        "-c",
        "/etc/rocketmq/broker.conf",
        "autoCreateTopicEnable=true"
      ]
    depends_on:
      - namesrv
    networks:
      - dev-network

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=namesrv:9876"
    depends_on:
      - namesrv
    networks:
      - dev-network

networks:
  dev-network:
    name: dev-network
